---
- name: Initial setup
  hosts: raspberry
  vars_files: ../vars/global.yaml
  become: yes
  tasks:
    - name: Apt update
      apt:
        update_cache: yes
        install_recommends: no
    - name: Apt upgrade
      apt:
        upgrade: safe
